-- INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('c++');
-- INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('c');
-- INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('linux');
-- INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('macos');
-- INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('performance');
-- INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('file');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('c++11') and id not in (select id from postsfiltered);
-- INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('ubuntu') and id not in (select id from postsfiltered);
-- INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('unix');
-- INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('memory');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('memory-management') and id not in (select id from postsfiltered);
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('file-io');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('io');
-- INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('linux-kernel');
-- INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('filesystems');
-- INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('kernel');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('hdfs');
-- INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('posix');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('driver');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('linux-device-driver');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('filestream');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('fstream');
-- INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('kernel-module');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('profile');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('profiler');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('adfs');
INSERT IGNORE INTO postsfiltesred SELECT * FROM posts where match(tags) against ('nsfilemanager');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('fs');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('nfs');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('gridfs');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('ntfs');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('posixct');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('adfs2.0');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('fsm');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('fseek');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('kernel-density');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('rdfs');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('kernel-extension');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('unix-socket');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('vfs');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('dfs');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('jcifs');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('gtfs');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('unix-domain-sockets');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('glusterfs');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('zfs');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('ifs');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('fscheck');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('lfs');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('posixlt');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('posix-ere');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('posix-api');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('posix-select');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('truevfs');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('mono-posix');
INSERT IGNORE INTO postsfiltered SELECT * FROM posts where match(tags) against ('kernel-methods');